### ISSUE TITLE
Esp-201 Measuring

### ISSUE THREAD

**Issue by meron1122** [wvanvlaenderen/ESP8266-Eagle_Library#2]
![eps8266 wymiary](https://cloud.githubusercontent.com/assets/2895090/7714397/883aea76-fe7e-11e4-8876-82ecb72da2f2.png)
My measuring of esp-201.

You are requested this on esp8266 forum so i think this can be helpfull.

Cheers

**Comment by Rene79** [comment]
@wvanvlaenderen issue can be closed
