### ISSUE TITLE
ESP-07-16pins no longer in the library

### ISSUE THREAD

**Issue by marciogranzotto** [wvanvlaenderen/ESP8266-Eagle_Library#4]
In commit 169ac30357c47562e797bbce19c6568ee636b40c the ESP-07 with 16 pins was removed.

**Comment by Rene79** [comment]
the commit 7b4fe936b52c10ca23fcf41f00ca8d1713d3b274 fixed that issue.

**Comment by Rene79** [comment]
Issue closed

**Comment by Rene79** [comment]
@wvanvlaenderen issue an be closed

**Comment by Rene79** [comment]
fixed in commit 7b4fe936b52c10ca23fcf41f00ca8d1713d3b274
closed
